version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/.github/workflows/requirements"
    schedule:
      interval: "weekly"
    ignore:
      # setuptools releases new versions almost daily
      - dependency-name: "setuptools"
        update-types: ["version-update:semver-patch"]
