application:
- changed-files:
  - any-glob-to-any-file:
    - repo/**

ci:
- changed-files:
  - any-glob-to-any-file:
    - .github/**

configs:
- changed-files:
  - any-glob-to-any-file:
    - configs/**
    - var/sys_repo/**    

dependencies:
- changed-files:
  - any-glob-to-any-file:
    - .github/worklflows/requirements/**
    - pyproject.toml

docs:
- changed-files:
  - any-glob-to-any-file:
    - docs/**
    - README.rst
    - tags.yaml

experiment:
- changed-files:
  - any-glob-to-any-file:
    - experiments/**
    - var/exp_repo/**
