# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

system_definition:
  manufacturer:
    vendor: PenguinComputing
    PCB: RelionCluster
  processor:
    vendor: Intel
    CPU: XeonPlatinum924248C
  interconnect:
    vendor: Intel
    network: OmniPath
  software:
    operating-system:
      name: Linux/TOSS
      tested: Linux/TOSS
    default-compiler:
      CPU-compiler: GCC
      spack_spec: xl@16.1.1-2022.08.19-cuda11.8.0
    default-mpi:
      name: MVAPICH
      spack_spec: mvapich2@2.3.7-gcc1211
    math-library:
      - name: BLAS
        spack_spec: intel-oneapi-mkl@2022.1.0
      - name: LAPACK
        spack_spec: intel-oneapi-mkl@2022.1.0
  system-tested:
    owner: LLNL
    name: magma
    installation-year: 2019
    description: [top500](https://www.top500.org/system/179774)
