# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

compilers:
- compiler:
    spec: fj@4.10.0
    modules: []
    paths:
      cc: /opt/FJSVxtclanga/tcsds-1.2.38/bin/fcc
      cxx: /opt/FJSVxtclanga/tcsds-1.2.38/bin/FCC
      f77: /opt/FJSVxtclanga/tcsds-1.2.38/bin/frt
      fc: /opt/FJSVxtclanga/tcsds-1.2.38/bin/frt
    flags: {}
    operating_system: rhel8
    target: aarch64
    environment:
      set:
        fcc_ENV: -Nclang
        FCC_ENV: -Nclang
      prepend_path:
        PATH: /opt/FJSVxtclanga/tcsds-1.2.38/bin
        LD_LIBRARY_PATH: /opt/FJSVxtclanga/tcsds-1.2.38/lib64
    extra_rpaths: []
- compiler:
    spec: fj@4.8.1
    modules: []
    paths:
      cc: /opt/FJSVxtclanga/tcsds-1.2.36/bin/fcc
      cxx: /opt/FJSVxtclanga/tcsds-1.2.36/bin/FCC
      f77: /opt/FJSVxtclanga/tcsds-1.2.36/bin/frt
      fc: /opt/FJSVxtclanga/tcsds-1.2.36/bin/frt
    flags: {}
    operating_system: rhel8
    target: aarch64
    environment:
      set:
        fcc_ENV: -Nclang
        FCC_ENV: -Nclang
      prepend_path:
        PATH: /opt/FJSVxtclanga/tcsds-1.2.36/bin
        LD_LIBRARY_PATH: /opt/FJSVxtclanga/tcsds-1.2.36/lib64
    extra_rpaths: []
- compiler:
    spec: fj@4.8.0
    modules: []
    paths:
      cc: /opt/FJSVxtclanga/tcsds-1.2.35/bin/fcc
      cxx: /opt/FJSVxtclanga/tcsds-1.2.35/bin/FCC
      f77: /opt/FJSVxtclanga/tcsds-1.2.35/bin/frt
      fc: /opt/FJSVxtclanga/tcsds-1.2.35/bin/frt
    flags: {}
    operating_system: rhel8
    target: aarch64
    environment:
      set:
        fcc_ENV: -Nclang
        FCC_ENV: -Nclang
      prepend_path:
        PATH: /opt/FJSVxtclanga/tcsds-1.2.35/bin
        LD_LIBRARY_PATH: /opt/FJSVxtclanga/tcsds-1.2.35/lib64
    extra_rpaths: []
- compiler:
    spec: fj@4.7.0
    modules: []
    paths:
      cc: /opt/FJSVxtclanga/tcsds-1.2.34/bin/fcc
      cxx: /opt/FJSVxtclanga/tcsds-1.2.34/bin/FCC
      f77: /opt/FJSVxtclanga/tcsds-1.2.34/bin/frt
      fc: /opt/FJSVxtclanga/tcsds-1.2.34/bin/frt
    flags: {}
    operating_system: rhel8
    target: aarch64
    environment:
      set:
        fcc_ENV: -Nclang
        FCC_ENV: -Nclang
      prepend_path:
        PATH: /opt/FJSVxtclanga/tcsds-1.2.34/bin
        LD_LIBRARY_PATH: /opt/FJSVxtclanga/tcsds-1.2.34/lib64
    extra_rpaths: []
- compiler:
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    operating_system: rhel8
    target: aarch64
    modules: []
    environment:
      unset: []
    extra_rpaths: []
    flags: {}
    spec: gcc@8.5.0
- compiler:
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    operating_system: rhel8
    target: x86_64
    modules: []
    environment:
      unset: []
    extra_rpaths: []
    flags: {}
    spec: gcc@8.4.1
- compiler:
    spec: gcc@12.2.0
    paths:
      cc: /vol0004/apps/oss/spack-v0.19/opt/spack/linux-rhel8-skylake_avx512/gcc-8.4.1/gcc-12.2.0-bjidm56oz6mejysl3wvjr3mbn7sqk3ec/bin/gcc
      cxx: /vol0004/apps/oss/spack-v0.19/opt/spack/linux-rhel8-skylake_avx512/gcc-8.4.1/gcc-12.2.0-bjidm56oz6mejysl3wvjr3mbn7sqk3ec/bin//g++
      f77: /vol0004/apps/oss/spack-v0.19/opt/spack/linux-rhel8-skylake_avx512/gcc-8.4.1/gcc-12.2.0-bjidm56oz6mejysl3wvjr3mbn7sqk3ec/bin/gfortran
      fc:  /vol0004/apps/oss/spack-v0.19/opt/spack/linux-rhel8-skylake_avx512/gcc-8.4.1/gcc-12.2.0-bjidm56oz6mejysl3wvjr3mbn7sqk3ec/bin/gfortran
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@12.2.0
    paths:
      cc: /vol0004/apps/oss/spack-v0.19/opt/spack/linux-rhel8-a64fx/gcc-8.5.0/gcc-12.2.0-sxcx7kmt3qiktffgzzvrj2wmup3g32bc/bin/gcc
      cxx: /vol0004/apps/oss/spack-v0.19/opt/spack/linux-rhel8-a64fx/gcc-8.5.0/gcc-12.2.0-sxcx7kmt3qiktffgzzvrj2wmup3g32bc/bin/g++
      f77: /vol0004/apps/oss/spack-v0.19/opt/spack/linux-rhel8-a64fx/gcc-8.5.0/gcc-12.2.0-sxcx7kmt3qiktffgzzvrj2wmup3g32bc/bin/gfortran
      fc: /vol0004/apps/oss/spack-v0.19/opt/spack/linux-rhel8-a64fx/gcc-8.5.0/gcc-12.2.0-sxcx7kmt3qiktffgzzvrj2wmup3g32bc/bin/gfortran
    flags: {}
    operating_system: rhel8
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []
