workflow:
  rules:
    # Always allow scheduled pipelines
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always

    # Always allow manually started pipelines
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always

    # Feature branch pipelines should diff against the integration target.
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "develop"
      changes:
        compare_to: refs/heads/develop
        paths: &workflow_change_paths
          - .gitlab/**/*
          - bin/**/*
          - configs/**/*
          - experiments/**/*
          - lib/**/*
          - modifiers/**/*
          - repos/**/*
          - var/**/*
          - systems/llnl-elcapitan/system.py
          - systems/llnl-cluster/system.py
          - .gitlab-ci.yml
          - checkout-versions.yaml
          - CTestConfig.cmake
          - CTestGitlab.cmake
          - pyproject.toml
          - remote-urls.yaml
          - requirements.txt

    # Develop pipelines should diff against the previous develop commit.
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "develop"
      changes: *workflow_change_paths

    # Otherwise, don't create a pipeline
    - when: never
variables:
  LLNL_SERVICE_USER: benchpark
  # Required information about GitHub repository
  GITHUB_PROJECT_NAME: benchpark
  GITHUB_PROJECT_ORG: LLNL
  # Override the pattern describing branches that will skip the "draft PR filter
  # test".  Add protected branches here. See default value in
  # preliminary-ignore-draft-pr.yml.
  ALWAYS_RUN_PATTERN: ^develop$|^master$|^v[0-9.]*$|^releases/$
  # Expand multi-line commands in logs
  FF_SCRIPT_SECTIONS: 1
  # clean up the repository after the job finishes
  FF_ENABLE_JOB_CLEANUP: 'true'
  GIT_STRATEGY: fetch
  # Debugging logs on gitlab
  # CI_DEBUG_TRACE: 'true'
  # Job variables
  ALLOC_NAME: ${CI_PROJECT_NAME}_ci_${CI_PIPELINE_ID}
  FLUX_ARGS: -N 1 --exclusive
  # Dane
  DANE_SHARED_ALLOC: -N 1 -t 04:00:00 --exclusive --reservation=ci
  # Matrix (NODES ARE SHARED WITHOUT --exclusive)
  MATRIX_SHARED_ALLOC: -N 1 -t 04:00:00 --exclusive
  # Tuolumne (max 4hr policy)
  TUOLUMNE_SHARED_ALLOC: -N 1 -t 4h --queue=pci --exclusive --setattr=gpumode=${GPUMODE}
    --conf=resource.rediscover=true
  # Tioga (max 2hr policy)
  TIOGA_SHARED_ALLOC: -N 1 -t 2h --queue=pci --exclusive
  CUSTOM_CI_BUILDS_DIR: $$HOME/.jacamar-ci/$CI_PIPELINE_ID
  # Dir cleanup can take awhile
  RUNNER_AFTER_SCRIPT_TIMEOUT: 20m
default:
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://lc.llnl.gov/gitlab
  interruptible: true
include:
  # [Optional] checks preliminary to running the actual CI test
  - project: radiuss/radiuss-shared-ci
    ref: v2024.12.0
    file:
      - utilities/preliminary-ignore-draft-pr.yml
      - utilities/skip-branch-not-a-pr.yml
  # Daily tests (from PRs)
  - local: .gitlab/tests/shared_flux_clusters.yml
  - local: .gitlab/tests/shared_slurm_clusters.yml
  # Nightly tests
  - local: .gitlab/tests/nightly.yml
stages:
  - bootstrap-benchpark
  - machine-checks
  - allocate-resources
  - test
  - release-resources
  - summarize
  - deploy-performance
  - cleanup-dir
bootstrap_benchpark:
  tags: [shell, oslic]
  stage: bootstrap-benchpark
  script:
    - . /usr/workspace/benchpark-dev/benchpark-venv/$SYS_TYPE/bin/activate
    - ./bin/benchpark configure --bootstrap-location $CUSTOM_CI_BUILDS_DIR
    - ./bin/benchpark bootstrap
generate_test_summary:
  tags: [shell, oslic]
  stage: summarize
  script:
    - . /usr/workspace/benchpark-dev/benchpark-venv/$SYS_TYPE/bin/activate
    - ./bin/benchpark configure --bootstrap-location $CUSTOM_CI_BUILDS_DIR
    - bash .gitlab/utils/aggregate-test-metadata.sh
    - python .gitlab/utils/generate_test_status_table.py artifact-test-summary/test_metadata_summary.json
  artifacts:
    when: always
    paths: [artifact-test-summary/]
  rules:
    - when: always
deploy_nightly_performance_metadata:
  tags: [shell, oslic]
  stage: deploy-performance
  needs:
    - job: generate_test_summary
      artifacts: true
  script:
    - bash .gitlab/utils/push-to-perf-repo.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: never
cleanup_pipeline_dir:
  tags: [shell, oslic]
  stage: cleanup-dir
  script:
    - CLEANUP_CI_BUILDS_DIR="${CUSTOM_CI_BUILDS_DIR/#\$HOME/$HOME}"
    - echo "Removing $CLEANUP_CI_BUILDS_DIR"
    - rm -rf "$CLEANUP_CI_BUILDS_DIR"
  rules:
    - when: always
