[project]
name="benchpark"
description="An open collaborative repository for cross site benchmarking environments"
readme = "README.rst"
requires-python = ">=3.8"
dynamic = ["version"]

[tool.setuptools]
packages = [
  "lib",
]

[tool.ruff]
line-length = 88
target-version = "py38"
builtins = ["IPython"]
force-exclude = true
extend-exclude = [
  "build",
  "lib/benchpark/test_repo",
  "repos",
]
include = ["*.py", "*.pyi", "bin/benchpark"]
src = ["lib"]

[tool.ruff.lint]
select = ["E", "F", "I", "W"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"experiments/hpl/experiment.py" = ["I"]
"legacy/modifiers/*/modifier.py" = ["F403", "F405"]
"modifiers/*/modifier.py" = ["F403", "F405"]

[tool.ruff.format]
exclude = [
  ".github/**",
]

[tool.codespell]
skip = './docs/_build,./docs/_static,./taxonomy.yaml,./repos/spack_repo/*/*/*/*.patch'
ignore-words-list = 'fom'

[tool.yamlfix]
line-length = 88
allow_duplicate_keys = true
explicit_start = false

[project.optional-dependencies]
analyze = [
  "llnl-hatchet>=2025.2.0",
  "llnl-thicket[plotting]>=2026.1.0",
  "matplotlib"
]
