# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

system_definition:
  name: Penguin-XeonPlatinum-OmniPath
  manufacturer:
    vendor: PenguinComputing
    name: RelionCluster
  processor:
    vendor: Intel
    name: XeonPlatinum924248C
    ISA: x86_64
    uArch: IceLake-SP
  accelerator:
    vendor: None
    name: None
    ISA: None
    uArch: None
  interconnect:
    vendor: Intel
    name: OmniPath
  OS:
    name: Linux/TOSS4
  system-tested:
    owner: LLNL
    name: magma
    installation-year: 2019
    description: [top500](https://www.top500.org/system/179774)
