compilers:
- compiler:
    spec: gcc@12.1.1
    paths:
      cc: /usr/tce/packages/gcc/gcc-12.1.1/bin/gcc
      cxx: /usr/tce/packages/gcc/gcc-12.1.1/bin/g++
      f77: /usr/tce/packages/gcc/gcc-12.1.1/bin/gfortran
      fc: /usr/tce/packages/gcc/gcc-12.1.1/bin/gfortran
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@2021.6.0-classic
    paths:
      cc: /usr/tce/packages/intel-classic/intel-classic-2021.6.0/bin/icc
      cxx: /usr/tce/packages/intel-classic/intel-classic-2021.6.0/bin/icpc
      f77: /usr/tce/packages/intel-classic/intel-classic-2021.6.0/bin/ifort
      fc: /usr/tce/packages/intel-classic/intel-classic-2021.6.0/bin/ifort
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
