# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

variables:
  modifier_package_name: 'caliper-cuda'
  modifier_spack_variant: '+caliper'

modifiers:
  - name: caliper-cuda
    mode: cuda

software:
  packages:
    caliper-cuda:
      pkg_spec: caliper+adiak+mpi~libunwind~libdw~papi+cuda cuda_arch=={cuda_arch}

