spack:
  packages:
    default-compiler:
      spack_spec: gcc@7.3.1
    default-mpi:
      spack_spec: openmpi@4.1.5-gcc731
    compiler-gcc:
      spack_spec: gcc@7.3.1
    lapack:
      spack_spec: lapack@3.4.2
    mpi-gcc:
      spack_spec: openmpi@4.1.5-gcc731
