# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

variables:
  gtl_flag: ''  # to be overwritten by tests that need GTL
  rocm_arch: 'gfx90a'
  batch_time: '120m'
  mpi_command: 'flux run -N {n_nodes} -n {n_ranks}'
  batch_submit: 'flux batch {execute_experiment}'
  batch_nodes: '# flux: -N {n_nodes}'
  batch_ranks: '# flux: -n {n_ranks}'
  batch_timeout: '# flux: -t {batch_time}'
