# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

spack:
  packages:
    default-compiler:
      spack_spec: gcc@=11.2.1
    default-mpi:
      spack_spec: mvapich2@2.3.7
    compiler-gcc:
      spack_spec: gcc@=11.2.1
    cublas-cuda:
      spack_spec: cublas@{default_cuda_version}
    lapack:
      spack_spec: intel-oneapi-mkl@2022.1.0
