# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

spack:
  packages:
    default-compiler:
      spack_spec: gcc@=11.2.1
    default-mpi:
      spack_spec: mvapich2@2.3.7-gcc-11.2.1
    compiler-gcc:
      spack_spec: gcc@=11.2.1
    compiler-clang:
      spack_spec: clang@=14.0.6
    mpi-clang:
      spack_spec: mvapich2@2.3.7-clang-14.0.6
    blas:
      spack_spec: intel-oneapi-mkl@2022.1.0
    cublas-cuda:
      spack_spec: cublas@{default_cuda_version}
    lapack:
      spack_spec: intel-oneapi-mkl@2022.1.0
    fftw:
      spack_spec: intel-oneapi-mkl@2022.1.0
