# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

variables:
  gtl_flag: ''  # to be overwritten by tests that need GTL
  cuda_arch: '60'
  default_cuda_version: '11.8.0'
  batch_time: '02:00'
  mpi_command: 'srun -N {n_nodes} -n {n_ranks}'
  batch_submit: 'sbatch {execute_experiment}'
  batch_nodes: '#SBATCH -N {n_nodes}'
  batch_ranks: '#SBATCH -n {n_ranks} -G {n_ranks}'
  batch_timeout: '#SBATCH -t {batch_time}:00'
