# Copyright 2023-2024 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

system_definition:
  name: RIKEN-Fugaku-Fujitsu-A64FX-TofuD
  integrator:
    vendor: Fujitsu
    name:
  processor:
    vendor: ARM
    name: A64FX
    ISA: Armv8.2-A-SVE
    uArch: A64FX
  accelerator:
    vendor:
    name:
    ISA:
    uArch:
  interconnect:
    vendor: Fujitsu
    name: TofuD
  system-tested:
    site: RIKEN
    name: Fugaku
    installation-year: 2020
    description: top500 <https://www.top500.org/system/179807>
  top500-system-instances:
    - Fugaku (RIKEN)
