ramble:
  config:
    deprecated: true
    spack_flags:
      install: '--add --keep-stage'
      concretize: '-U -f'
  variables:
    mpi_command: '/usr/tcetmp/bin/lrun -n {n_ranks} -T {processes_per_node}'
    batch_submit: 'bsub {execute_experiment}'
  applications:
    saxpy:
      workloads:
        problem:
          variables:
            n_ranks: '{processes_per_node} * {n_nodes}'
            batch_time: '120'
          experiments:
            saxpy_{n}_{n_nodes}_{processes_per_node}_{n_ranks}:
              variables:
                processes_per_node: '4'
                n_nodes: '1'
                n: ['128', '256', '512', '1024']
              matrix:
                  - n
  spack:
    concretized: true
    packages:
      xl2022.08.19cuda11.7.0:
        spack_spec: xl@16.1.1-2022.08.19-cuda11.7.0
      spectrummpi2022.08.19:
        spack_spec: spectrum-mpi@2022.08.19-cuda-11.7.0
      saxpy:
        spack_spec: saxpy@1.0.0 +cuda cuda_arch=70 ^cuda@11.7.0
        compiler: xl2022.08.19cuda11.7.0
    environments:
      saxpy:
        packages:
        - spectrummpi2022.08.19
        - saxpy
