spack:
  packages:
    compiler-cuda{cuda_version}:
      spack_spec: xl@16.1.1-{xl_version}-cuda{cuda_version}
    default_compiler:
      spack_spec: xl@16.1.1-{xl_version}-cuda{default_cuda}
    cublas{cuda_version}:
      spack_spec: cublas@{cuda_version}
    lapack:
      spack_spec: lapack-xl@3.9.0
    default_mpi:
      spack_spec: spectrum-mpi@{mpi_version}
    mpi-{compilers}:
      spack_spec: spectrum-mpi@{mpi_version}
