# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

AWS-ParallelCluster3.7.2_x86_none_EFA

system_definition:
  manufacturer:
    vendor: AWS
    PCB: ParallelCluster3.7.2
  processor:
    CPU: x86
  accelerator:
    GPU: none
  interconnect:
    vendor: AWS
    network: EFA
  software:
    operating-system:
      name: any-OS
      tested: Amazon-Linux-2
    default-compiler:
      CPU-compiler: GCC
      GPU-compiler: na
      spack_spec: gcc@7.3.1
    default-mpi:
      name: OpenMPI
      spack_spec: openmpi@4.1.5-gcc731
    math-library:
      - name: BLAS
        spack_spec: blas@3.4.2
      - name: LAPACK
        spack_spec: lapack@3.4.2
  system-tested:
    owner: AWS
    name: ParallelCluster3.7.2
    installation-year: 2023
    description: [AWS-efa-instatnce-types](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa.html#efa-instance-types)
