# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

compilers:
- compiler:
    spec: xl@16.1.1-2023.06.28-cuda-11.8.0-gcc-11.2.1
    paths:
      cc: /usr/tce/packages/xl/xl-2023.06.28-cuda-11.8.0-gcc-11.2.1/bin/xlc
      cxx: /usr/tce/packages/xl/xl-2023.06.28-cuda-11.8.0-gcc-11.2.1/bin/xlC
      f77: /usr/tce/packages/xl/xl-2023.06.28-cuda-11.8.0-gcc-11.2.1/bin/xlf
      fc: /usr/tce/packages/xl/xl-2023.06.28-cuda-11.8.0-gcc-11.2.1/bin/xlf
    flags:
      cflags: -g -O2
      cxxflags: -g -O2 -std=c++14
      fflags: -g -O2
    operating_system: rhel7
    target: ppc64le
    modules: [cuda/11.8.0, xl/2023.06.28-cuda-11.8.0-gcc-11.2.1]
    environment: {}
    extra_rpaths: []
- compiler:
    spec: xl@16.1.1-2022.08.19-cuda-11.7.0
    paths:
      cc: /usr/tce/packages/xl/xl-2022.08.19/bin/xlc
      cxx: /usr/tce/packages/xl/xl-2022.08.19/bin/xlC
      f77: /usr/tce/packages/xl/xl-2022.08.19/bin/xlf
      fc: /usr/tce/packages/xl/xl-2022.08.19/bin/xlf
    flags:
      cflags: -g -O2
      cxxflags: -g -O2 -std=c++14
      fflags: -g -O2
    operating_system: rhel7
    target: ppc64le
    modules: [cuda/11.7.0, xl/2022.08.19-cuda-11.7.0]
    environment: {}
    extra_rpaths: []
- compiler:
    spec: xl@16.1.1-2022.08.19-cuda10.1.243
    paths:
      cc: /usr/tce/packages/xl/xl-2022.08.19/bin/xlc
      cxx: /usr/tce/packages/xl/xl-2022.08.19/bin/xlC
      f77: /usr/tce/packages/xl/xl-2022.08.19/bin/xlf
      fc: /usr/tce/packages/xl/xl-2022.08.19/bin/xlf
    flags:
      cflags: -g -O2
      cxxflags: -g -O2 -std=c++14
      fflags: -g -O2
    operating_system: rhel7
    target: ppc64le
    modules: [cuda/10.1.243, xl/2022.08.19] # TODO: Make these available to ramble or remove them entirely
    environment: {}
    extra_rpaths: []
- compiler:
    spec: xl@16.1.1-2022.08.19-cuda11.8.0
    paths:
      cc: /usr/tce/packages/xl/xl-2022.08.19-cuda-11.8.0/bin/xlc
      cxx: /usr/tce/packages/xl/xl-2022.08.19-cuda-11.8.0/bin/xlC
      f77: /usr/tce/packages/xl/xl-2022.08.19-cuda-11.8.0/bin/xlf
      fc: /usr/tce/packages/xl/xl-2022.08.19-cuda-11.8.0/bin/xlf
    flags: # TODO: Fix spack concretization bug
      cflags: -g -O2
      cxxflags: -g -O2 -std=c++14
      fflags: -g -O2
    operating_system: rhel7
    target: ppc64le
    modules: [cuda/11.8.0, xl/2022.08.19-cuda-11.8.0] # TODO: Make these available to ramble or remove them entirely
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@8.3.1
    paths:
      cc: /usr/tce/packages/gcc/gcc-8.3.1/bin/gcc
      cxx: /usr/tce/packages/gcc/gcc-8.3.1/bin/g++
      f77: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
      fc: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
    flags: {}
    operating_system: rhel7
    target: ppc64le
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@16.0.6-cuda11.8.0
    paths:
      cc: /usr/tce/packages/clang/clang-16.0.6-cuda-11.8.0-gcc-11.2.1/bin/clang
      cxx: /usr/tce/packages/clang/clang-16.0.6-cuda-11.8.0-gcc-11.2.1/bin/clang++
      f77: /usr/tce/packages/gcc/gcc-11.2.1/bin/gfortran
      fc: /usr/tce/packages/gcc/gcc-11.2.1/bin/gfortran
    flags:
      cflags: -g -O2
      cxxflags: -g -O2 -std=c++17
      fflags: ''
    operating_system: rhel7
    target: ppc64le
    modules: []
    environment: {}
    extra_rpaths: []
