# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

spack:
  packages:
    default-compiler:
      spack_spec: gcc@12.1.1
    default-mpi:
      spack_spec: mvapich2@2.3.7-gcc1211
    compiler-gcc:
      spack_spec: gcc@12.1.1
    compiler-intel:
      spack_spec: intel@2021.6.0-classic
    blas:
      spack_spec: intel-oneapi-mkl@2022.1.0
    lapack:
      spack_spec: intel-oneapi-mkl@2022.1.0
    mpi-gcc:
      spack_spec: mvapich2@2.3.7-gcc1211
    mpi-intel:
      spack_spec: mvapich2@2.3.7-intel202160classic
