# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

spack:
  packages:
    default-compiler:
      spack_spec: cce@16.0.0-rocm5.5.1
    default-mpi:
      spack_spec: cray-mpich@8.1.26%cce ~gtl
    compiler-rocm:
      spack_spec: cce@16.0.0-rocm5.5.1
    blas-rocm:
      spack_spec: rocblas@5.5.1
    blas:
      spack_spec: rocblas@5.5.1
    lapack:
      spack_spec: cray-libsci@23.05.1.4
    mpi-rocm-gtl:
      spack_spec: cray-mpich@8.1.26%cce +gtl
    mpi-rocm-no-gtl:
      spack_spec: cray-mpich@8.1.26%cce ~gtl
    mpi-gcc:
      spack_spec: cray-mpich@8.1.26%gcc ~gtl
