# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

variables:
  gtl_flag: ''  # to be overwritten by tests that need GTL
  rocm_arch: 'gfx90a'
  scheduler: 'flux'
  flux_batch_time: '120m'
  slurm_batch_time: '02:00'
  batch_time: '{{scheduler}_batch_time}'
  flux_mpi_command: 'flux run -N {n_nodes} -n {n_ranks}'
  flux_batch_submit: 'flux batch {execute_experiment}'
  flux_batch_nodes: '# flux: -N {n_nodes}'
  flux_batch_ranks: '# flux: -n {n_ranks}'
  flux_batch_timeout: '# flux: -t {batch_time}'
  slurm_mpi_command: 'srun -N {n_nodes} -n {n_ranks}'
  slurm_batch_submit: 'sbatch {execute_experiment}'
  slurm_batch_nodes: '#SBATCH -N {n_nodes}'
  slurm_batch_ranks: '#SBATCH -n {n_ranks}'
  slurm_batch_timeout: '#SBATCH -t {batch_time}:00'
  mpi_command: '{{scheduler}_mpi_command}'
  batch_submit: '{{scheduler}_batch_submit}'
  batch_nodes: '{{scheduler}_batch_nodes}'
  batch_ranks: '{{scheduler}_batch_ranks}'
  batch_timeout: '{{scheduler}_batch_timeout}'
