# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

system_definition:
  name: JUWELS
  site: 
  system: 
  integrator:
    vendor: 
    name:
  processor:
    vendor: 
    name: 
    ISA: x86_64
    uArch: 
  accelerator:
    vendor: NVIDIA
    name: A100
    ISA: PTX
    uArch: sm_80
  interconnect:
    vendor: Mellanox
    name: Infiniband
  system-tested:
    site: JSC
    name: 
    installation-year: 2020
    description:
  top500-system-instances:
    -
