spack:
  packages:
    default-compiler:
      spack_spec: gcc
    compiler-gcc:
      spack_spec: gcc
    compiler-intel:
      spack_spec: intel
    default-mpi:
      spack_spec: openmpi
    lapack:
      spack_spec: lapack
