spack:
  packages:
    default-compiler:
      spack_spec: gcc
    default-mpi:
      spack_spec: openmpi
    lapack:
      spack_spec: intel-oneapi-mkl@2022.1.0
    mpi-{compilers}:
      spack_spec: openmpi
