# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

system_definition:
  name: x86
  manufacturer:
    vendor: ""
    name: ""
  processor:
    vendor: ""
    name: ""
    ISA: x86_64
  accelerator:
    vendor: ""
    name: ""
    GPU_ISA: ""
  interconnect:
    vendor: ""
    name: ""
  OS:
    name: ""
  system-tested:
    owner: ""
    name: ""
    installation-year: ""
    description: ""
