# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

system_definition:
  manufacturer:
    vendor: IBM
    name: AC922
  processor:
    vendor: IBM
    name: POWER9
    ISA: POWER-3.0B
  accelerator:
    vendor: NVIDIA
    name: V100
    GPU-ISA: sm_70
  interconnect:
    vendor: Mellanox
    name: EDR-Infiniband
  OS:
    name: RHEL
  system-tested:
    owner: LLNL
    name: sierra
    installation-year: 2018
    description: [top500](https://www.top500.org/system/179398)
