# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

variables:
  caliper_base: 'caliper'
  caliper_base_variant: '+caliper'
  caliper_base_name: 'caliper'
  caliper_base_mode: 'time'

  caliper_cuda: 'caliper_cuda'
  caliper_cuda_variant: '+caliper'
  caliper_cuda_name: 'caliper-cuda'
  caliper_cuda_mode: 'cuda'

  modifier: 'caliper_cuda'
  modifier_variant: '{{modifier}_variant}'
  modifier_name: '{{modifier}_name}'
  modifier_mode: '{{modifier}_mode}'
