# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

software:
  packages:
    default-compiler:
      pkg_spec: clang@16.0.6-ibm-cuda-{default_cuda_version}-gcc-11.2.1
    default-mpi:
      pkg_spec: spectrum-mpi@2023.06.28-clang-ibm-16.0.6-cuda-{default_cuda_version}-gcc-11.2.1
    compiler-xl:
      pkg_spec: xl@16.1.1-2023.06.28-cuda-{default_cuda_version}-gcc-11.2.1
    mpi-xl:
      pkg_spec: spectrum-mpi@2023.06.28-cuda-{default_cuda_version}-gcc-11.2.1
    compiler-gcc:
      pkg_spec: gcc@8.3.1
    compiler-clang:
      pkg_spec: clang@16.0.6-cuda{default_cuda_version}
    mpi-clang:
      pkg_spec: spectrum-mpi@2022.08.19-clang16.0.6-cuda-{default_cuda_version}
    mpi-gcc:
      pkg_spec: spectrum-mpi@2022.08.19-gcc-8.3.1
    compiler-clang-ibm:
      pkg_spec: clang@16.0.6-ibm-cuda-{default_cuda_version}-gcc-11.2.1
    mpi-clang-ibm:
      pkg_spec: spectrum-mpi@2023.06.28-clang-ibm-16.0.6-cuda-{default_cuda_version}-gcc-11.2.1
    blas:
      pkg_spec: cublas@{default_cuda_version}
    cublas-cuda:
      pkg_spec: cublas@{default_cuda_version}
    lapack:
      pkg_spec: lapack-xl@3.9.0
    fftw:
      pkg_spec: fftw@3.3.10
