# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

spack:
  packages:
    default-compiler:
      spack_spec: clang@16.0.6-cuda{default_cuda_version}
    default-mpi:
      spack_spec: spectrum-mpi@2022.08.19-clang16.0.6-cuda{default_cuda_version}
    compiler-gcc:
      spack_spec: gcc@8.3.1
    blas:
      spack_spec: blas@3.6.0
    cublas-cuda:
      spack_spec: cublas@{default_cuda_version}
    lapack:
      spack_spec: lapack-xl@3.6.0
    fftw:
      spack_spec: fftw@3.3.10
