# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

packages:
  all:
    require: 'target=x86_64:'
    variants: amdgpu_target=gfx90a
  tar:
    externals:
    - spec: tar@1.30
      prefix: /usr

# tar above is an example of how to (optionally) specify the external packages Spack should use (and not build)
# you can use 'spack external find' to find the packages available on your system
# (https://spack.readthedocs.io/en/v0.18.0/command_index.html#spack-external-find)
