# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

software:
  packages:
    default-compiler:
      pkg_spec: "{default_comp} {sys_arch}"
    default-mpi:
      pkg_spec: fujitsu-mpi@{fj_comp_version}%{default_comp} {sys_arch}
    blas:
      pkg_spec: fujitsu-ssl2@{fj_comp_version}%{default_comp} {sys_arch}
    lapack:
      pkg_spec: fujitsu-ssl2@{fj_comp_version}%{default_comp} {sys_arch}
    gmake:
      pkg_spec: gmake@4.2.1 {sys_arch}
    cmake:
      pkg_spec: cmake@3.20.2 {sys_arch}

