# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

software:
  packages:
    default-compiler:
      pkg_spec: clang@{default_llvm_version}
    default-mpi:
      pkg_spec: fujitsu-mpi@{default_fj_version}
      compiler: default-compiler
    compiler-clang:
      pkg_spec: clang@{default_llvm_version}
    compiler-fj:
      pkg_spec: fj@{default_fj_version}
    compiler-gcc:
      pkg_spec: gcc@{default_gnu_version}
    blas:
      pkg_spec: fujitsu-ssl2@{default_fj_version}
      compiler: default-compiler
    lapack:
      pkg_spec: fujitsu-ssl2@{default_fj_version}
      compiler: default-compiler
