# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

spack:
  packages:
    default-compiler:
      #spack_spec: fj@{default_fj_version}
      #spack_spec: clang@{default_llvm_version}
      spack_spec: gcc@{default_gnu_version}
    default-mpi:
      spack_spec: fujitsu-mpi@{default_fj_version} arch=linux-rhel8-a64fx
    compiler-fujitsu:
      spack_spec: fj@{default_fj_version}
    compiler-clang:
      spack_spec: clang@{default_llvm_version}
    compiler-gcc:
      spack_spec: gcc@{default_gnu_version}
    blas:
      spack_spec: fujitsu-ssl2@{default_fj_version} arch=linux-rhel8-a64fx
    lapack:
      spack_spec: fujitsu-ssl2@{default_fj_version} arch=linux-rhel8-a64fx
    fftw:
      spack_spec: fujitsu-ssl2@{default_fj_version} arch=linux-rhel8-a64fx
    mpi-fujitsu:
      spack_spec: fujitsu-mpi@{default_fj_version} arch=linux-rhel8-a64fx
    mpi-clang:
      spack_spec: fujitsu-mpi@{default_fj_version} arch=linux-rhel8-a64fx
    mpi-gcc:
      spack_spec: fujitsu-mpi@{default_fj_version} arch=linux-rhel8-a64fx
    gmake:
      spack_spec: gmake@4.2.1 arch=linux-rhel8-a64fx
    cmake:
      spack_spec: cmake@3.20.2 arch=linux-rhel8-a64fx

