# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

compilers:
- compiler:
    spec: cce@16.0.0-rocm5.5.1
    paths:
      cc:  /opt/cray/pe/cce/16.0.0/bin/craycc
      cxx:  /opt/cray/pe/cce/16.0.0/bin/crayCC
      f77:  /opt/cray/pe/cce/16.0.0/bin/crayftn
      fc:  /opt/cray/pe/cce/16.0.0/bin/crayftn
    flags:
      cflags: -g -O2
      cxxflags: -g -O2 -std=c++17
      fflags: -g -O2 -hnopattern
      ldflags: -ldl
    operating_system: rhel8
    target: x86_64
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /opt/cray/pe/cce/16.0.0/cce/x86_64/lib
    extra_rpaths: [/opt/cray/pe/cce/16.0.0/cce/x86_64/lib/, /opt/cray/pe/gcc-libs/]
- compiler:
    spec: rocmcc@5.5.1
    paths:
      cc:  /opt/rocm-5.5.1/bin/amdclang
      cxx:  /opt/rocm-5.5.1/bin/amdclang++
      f77: /opt/rocm-5.5.1/bin/amdflang 
      fc:  /opt/rocm-5.5.1/bin/amdflang
    flags:
      cflags: -g -O2
      cxxflags: -g -O2
    operating_system: rhel8
    target: x86_64
    modules: []
    environment:
      set:
        RFE_811452_DISABLE: '1'
      append_path:
        LD_LIBRARY_PATH: /opt/cray/pe/gcc-libs
      prepend_path:
        LD_LIBRARY_PATH: "/opt/cray/pe/cce/16.0.0/cce/x86_64/lib:/opt/cray/pe/pmi/6.1.12/lib"
        LIBRARY_PATH: /opt/rocm-5.5.1/lib
    extra_rpaths:
    - /opt/rocm-5.5.1/lib
    - /opt/cray/pe/gcc-libs
    - /opt/cray/pe/cce/16.0.0/cce/x86_64/lib
- compiler:
    spec: rocmcc@5.4.3
    paths:
      cc:  /opt/rocm-5.4.3/bin/amdclang
      cxx:  /opt/rocm-5.4.3/bin/amdclang++
      f77: /opt/rocm-5.4.3/bin/amdflang 
      fc:  /opt/rocm-5.4.3/bin/amdflang
    flags:
      cflags: -g -O2
      cxxflags: -g -O2
    operating_system: rhel8
    target: x86_64
    modules: []
    environment:
      set:
        RFE_811452_DISABLE: '1'
      append_path:
        LD_LIBRARY_PATH: /opt/cray/pe/gcc-libs
      prepend_path:
        LD_LIBRARY_PATH: "/opt/cray/pe/cce/16.0.0/cce/x86_64/lib:/opt/cray/pe/pmi/6.1.12/lib"
        LIBRARY_PATH: /opt/rocm-5.4.3/lib
    extra_rpaths:
    - /opt/rocm-5.4.3/lib
    - /opt/cray/pe/gcc-libs
    - /opt/cray/pe/cce/16.0.0/cce/x86_64/lib
- compiler:
    spec: gcc@12.2.0
    paths:
      cc: /opt/cray/pe/gcc/12.2.0/bin/gcc
      cxx: /opt/cray/pe/gcc/12.2.0/bin/g++
      f77: /opt/cray/pe/gcc/12.2.0/bin/gfortran
      fc: /opt/cray/pe/gcc/12.2.0/bin/gfortran
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
