# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

packages:
  all:
    require: 'target=x86_64:'
    variants: amdgpu_target=gfx90a
  tar:
    externals:
    - spec: tar@1.30
      prefix: /usr
  coreutils:
    externals:
    - spec: coreutils@8.30
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.1+lex
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@1.1.1k
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.3
      prefix: /usr
  cmake:
    buildable: false
    externals:
    - spec: cmake@3.20.2
      prefix: /usr
    - spec: cmake@3.23.1
      prefix: /usr/tce
    - spec: cmake@3.24.2
      prefix: /usr/tce
  pkgconf:
    externals:
    - spec: pkgconf@1.4.2
      prefix: /usr
  curl:
    externals:
    - spec: curl@7.61.1+gssapi+ldap+nghttp2
      prefix: /usr
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
  subversion:
    externals:
    - spec: subversion@1.10.2
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.6
      prefix: /usr
  swig:
    externals:
    - spec: swig@3.0.12
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@4.2.1
      prefix: /usr
  binutils:
    externals:
    - spec: binutils@2.30.113
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.6.0
      prefix: /usr
  git-lfs:
    externals:
    - spec: git-lfs@2.11.0
      prefix: /usr/tce
  ccache:
    externals:
    - spec: ccache@3.7.7
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.16.1
      prefix: /usr
  cvs:
    externals:
    - spec: cvs@1.11.23
      prefix: /usr
  git:
    externals:
    - spec: git@2.31.1+tcltk
      prefix: /usr
    - spec: git@2.29.1+tcltk
      prefix: /usr/tce
  openssh:
    externals:
    - spec: openssh@8.0p1
      prefix: /usr
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  texinfo:
    externals:
    - spec: texinfo@6.5
      prefix: /usr
  bison:
    externals:
    - spec: bison@3.0.4
      prefix: /usr
  python:
    buildable: false
    externals:
    - spec: python@3.9.12
      prefix: /usr/tce/packages/python/python-3.9.12
  hipfft:
    buildable: false
    externals:
    - spec: hipfft@5.4.3
      prefix: /opt/rocm-5.4.3
    - spec: hipfft@5.5.1
      prefix: /opt/rocm-5.5.1
  rocfft:
    buildable: false
    externals:
    - spec: rocfft@5.4.3
      prefix: /opt/rocm-5.4.3
    - spec: rocfft@5.5.1
      prefix: /opt/rocm-5.5.1
  rocprim:
    buildable: false
    externals:
    - spec: rocprim@5.4.3
      prefix: /opt/rocm-5.4.3
    - spec: rocprim@5.5.1
      prefix: /opt/rocm-5.5.1
  rocrand:
    buildable: false
    externals:
    - spec: rocrand@5.4.3
      prefix: /opt/rocm-5.4.3/hiprand
    - spec: rocrand@5.5.1
      prefix: /opt/rocm-5.5.1/hiprand
  rocsparse:
    buildable: false
    externals:
    - spec: rocsparse@5.4.3
      prefix: /opt/rocm-5.4.3
    - spec: rocsparse@5.5.1
      prefix: /opt/rocm-5.5.1
  rocthrust:
    buildable: false
    externals:
    - spec: rocthrust@5.4.3
      prefix: /opt/rocm-5.4.3
    - spec: rocthrust@5.5.1
      prefix: /opt/rocm-5.5.1
  hip:
    buildable: false
    externals:
    - spec: hip@5.4.3
      prefix: /opt/rocm-5.4.3
    - spec: hip@5.5.1
      prefix: /opt/rocm-5.5.1
  hsa-rocr-dev:
    buildable: false
    externals:
    - spec: hsa-rocr-dev@5.4.3
      prefix: /opt/rocm-5.4.3
    - spec: hsa-rocr-dev@5.5.1
      prefix: /opt/rocm-5.5.1
  comgr:
    buildable: false
    externals:
    - spec: comgr@5.4.3
      prefix: /opt/rocm-5.4.3/
    - spec: comgr@5.5.1
      prefix: /opt/rocm-5.5.1/
  hipsparse:
    buildable: false
    externals:
    - spec: hipsparse@5.4.3
      prefix: /opt/rocm-5.4.3
    - spec: hipsparse@5.5.1
      prefix: /opt/rocm-5.5.1
  hipblas:
    buildable: false
    externals:
    - spec: hipblas@5.4.3
      prefix: /opt/rocm-5.4.3/
    - spec: hipblas@5.5.1
      prefix: /opt/rocm-5.5.1/
  hsakmt-roct:
    buildable: false
    externals:
    - spec: hsakmt-roct@5.4.3
      prefix: /opt/rocm-5.4.3/
    - spec: hsakmt-roct@5.5.1
      prefix: /opt/rocm-5.5.1/
  roctracer-dev-api:
    buildable: false
    externals:
    - spec: roctracer-dev-api@5.4.3
      prefix: /opt/rocm-5.4.3/
    - spec: roctracer-dev-api@5.5.1
      prefix: /opt/rocm-5.5.1/
  rocminfo:
    buildable: false
    externals:
    - spec: rocminfo@5.4.3
      prefix: /opt/rocm-5.4.3/
    - spec: rocminfo@5.5.1
      prefix: /opt/rocm-5.5.1/
  llvm:
    buildable: false
    externals:
    - spec: llvm@15.0.0-5.4.3
      prefix: /opt/rocm-5.4.3/llvm
    - spec: llvm@16.0.0-5.5.1
      prefix: /opt/rocm-5.5.1/llvm
  llvm-amdgpu:
    buildable: false
    externals:
    - spec: llvm-amdgpu@5.4.3
      prefix: /opt/rocm-5.4.3/llvm
    - spec: llvm-amdgpu@5.5.1
      prefix: /opt/rocm-5.5.1/llvm
  rocblas:
    buildable: false
    externals:
    - spec: rocblas@5.4.3
      prefix: /opt/rocm-5.4.3
    - spec: rocblas@5.5.1
      prefix: /opt/rocm-5.5.1
  rocsolver:
    buildable: false
    externals:
    - spec: rocsolver@5.4.3
      prefix: /opt/rocm-5.4.3
    - spec: rocsolver@5.5.1
      prefix: /opt/rocm-5.5.1
  cray-libsci:
    buildable: false
    externals:
    - spec: cray-libsci@23.05.1.4%cce
      prefix: /opt/cray/pe/libsci/23.05.1.4/cray/12.0/x86_64/
    - spec: cray-libsci@23.05.1.4%gcc
      prefix: /opt/cray/pe/libsci/23.05.1.4/gnu/10.3/x86_64/
  lapack:
    buildable: false
  blas:
    buildable: false
  unzip:
    buildable: false
    externals:
    - spec: unzip@6.0
      prefix: /usr
  hypre:
    variants: amdgpu_target=gfx90a
  hwloc:
    buildable: false
    externals:
    - spec: hwloc@2.9.1
      prefix: /usr
  fftw:
    buildable: false
  intel-oneapi-mkl:
    buildable: false
    externals:
    - spec: intel-oneapi-mkl@2023.2.0
      prefix: /opt/intel/oneapi
  mpi:
    buildable: false
  libfabric:
    buildable: false
    externals:
    - spec: libfabric@2.1
      prefix: /opt/cray/libfabric/2.1
  cray-mpich:
    buildable: false
    externals:
    - spec: cray-mpich@8.1.26%cce@16.0.0 +gtl +wrappers
      prefix: /opt/cray/pe/mpich/8.1.26/ofi/crayclang/16.0
      extra_attributes:
        gtl_cutoff_size: 4096
        fi_cxi_ats: 0
        gtl_lib_path: /opt/cray/pe/mpich/8.1.26/gtl/lib
        ldflags: "-L/opt/cray/pe/mpich/8.1.26/ofi/crayclang/16.0/lib -lmpi -L/opt/cray/pe/mpich/8.1.26/gtl/lib -Wl,-rpath=/opt/cray/pe/mpich/8.1.26/gtl/lib -lmpi_gtl_hsa"
    - spec: cray-mpich@8.1.26%cce@16.0.0 ~gtl +wrappers
      prefix: /opt/cray/pe/mpich/8.1.26/ofi/crayclang/16.0
      extra_attributes:
        gtl_lib_path: /opt/cray/pe/mpich/8.1.26/gtl/lib
        ldflags: "-L/opt/cray/pe/mpich/8.1.26/ofi/crayclang/16.0/lib -lmpi -L/opt/cray/pe/mpich/8.1.26/gtl/lib -Wl,-rpath=/opt/cray/pe/mpich/8.1.26/gtl/lib"
    - spec: cray-mpich@8.1.26%gcc@12.2.0 ~gtl +wrappers
      prefix: /opt/cray/pe/mpich/8.1.26/ofi/gnu/10.3
      extra_attributes:
        gtl_lib_path: /opt/cray/pe/mpich/8.1.26/gtl/lib
        ldflags: "-L/opt/cray/pe/mpich/8.1.26/ofi/gnu/10.3/lib -lmpi -L/opt/cray/pe/mpich/8.1.26/gtl/lib -Wl,-rpath=/opt/cray/pe/mpich/8.1.26/gtl/lib"
