packages:
  tar:
    externals:
    - spec: tar@1.26
      prefix: /usr
      buildable: false
  cmake:
    externals:
    - spec: cmake@3.23.1
      prefix: /usr/tce/packages/cmake/cmake-3.23.1
      buildable: false
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr/tcetmp/packages/gmake/gmake-4.2.1
      buildable: false
  cuda:
    externals:
    - spec: cuda@11.7.0
      prefix: /usr/tce/packages/cuda/cuda-11.7.0 
      buildable: false
  mpi:
    externals:
    - spec: spectrum-mpi@2022.08.19-cuda-11.7.0
      prefix: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-xl-2022.08.19-cuda-11.7.0
      buildable: false
      extra_attributes:
        ldflags: "-lmpiprofilesupport -lmpi_ibm_usempi -lmpi_ibm_mpifh -lmpi_ibm"
