# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

compilers:
- compiler:
      spec: nvhpc@=23.7
      paths:
        cc: /p/software/juwelsbooster/stages/2024/software/NVHPC/23.7-CUDA-12/Linux_aarch64/23.7/compilers/bin/nvc
        cxx: /p/software/juwelsbooster/stages/2024/software/NVHPC/23.7-CUDA-12/Linux_aarch64/23.7/compilers/bin/nvc++
        f77: /p/software/juwelsbooster/stages/2024/software/NVHPC/23.7-CUDA-12/Linux_aarch64/23.7/compilers/bin/nvfortran
        fc: /p/software/juwelsbooster/stages/2024/software/NVHPC/23.7-CUDA-12/Linux_aarch64/23.7/compilers/bin/nvfortran
      operating_system: rocky8
      target: x86_64
      modules:
      - Stages/2024
      - NVHPC/23.7
      environment: {}
      extra_rpaths: []
- compiler:
      spec: gcc@=12.3.0
      paths:
        cc: /p/software/juwelsbooster/stages/2024/software/GCCcore/12.3.0/bin/gcc
        cxx: /p/software/juwelsbooster/stages/2024/software/GCCcore/12.3.0/bin/g++
        f77: /p/software/juwelsbooster/stages/2024/software/GCCcore/12.3.0/bin/gfortran
        fc: /p/software/juwelsbooster/stages/2024/software/GCCcore/12.3.0/bin/gfortran
      operating_system: rocky9
      target: aarch64
      modules:
      - Stages/2024
      - GCC/12.3.0
      environment: {}
      extra_rpaths: []
