# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

import pathlib

from benchpark.directives import variant
from benchpark.system import System


class CscsDaint(System):

    variant(
        "compiler",
        default="cce",
        values=("gcc9", "gcc10", "gcc11", "cce", "intel", "pgi"),
        description="Which compiler to use",
    )
    variant(
        "cuda",
        default="11.2.0",
        values=("11.2.0", "11.1.0", "11.0.207", "10.2.89"),
        description="CUDA version",
    )

    def initialize(self):
        super().initialize()

        sys_variables = {
            "sys_cores_per_node": 12,
            "sys_gpus_per_node": 1,
            "sys_mem_per_node": 64,
        }

        self.scheduler = "slurm"
        for k, v in sys_variables.items():
            setattr(self, k, v)

    def generate_description(self, output_dir):
        super().generate_description(output_dir)

        sw_description = pathlib.Path(output_dir) / "software.yaml"

        with open(sw_description, "w") as f:
            f.write(self.sw_description())

    def system_specific_variables(self):
        return {
            "11.2.0": "'11.2.0'",
            "cuda_arch": "'60'",
            "enable_mps": "'/usr/tcetmp/bin/enable_mps'"
        }

    def external_pkg_configs(self):
        externals = CscsDaint.resource_location / "externals"

        selections = [externals / "base" / "00-packages.yaml"]
        cuda_cfg_path = self.next_adhoc_cfg()
        with open(cuda_cfg_path, "w") as f:
            f.write(self.cuda_config(self.spec.variants["cuda"][0]))
        selections.append(cuda_cfg_path)

        return selections

    def compiler_configs(self):
        compilers = CscsDaint.resource_location / "compilers"
        selections = []
        if "cce" in self.spec.variants["compiler"][0]:
            selections.append(compilers / "02-cce-12-compiler.yaml")
        elif "gcc9" in self.spec.variants["compiler"][0]:
            selections.append(compilers  / "01-gcc-9-compiler.yaml")
        elif "gcc10" in self.spec.variants["compiler"][0]:
            selections.append(compilers / "03-gcc-10-compiler.yaml")
        elif "gcc11" in self.spec.variants["compiler"][0]:
            selections.append(compilers / "04-gcc-11-compiler.yaml")
        elif "intel" in self.spec.variants["compiler"][0]:
            selections.append(compilers / "05-intel-compiler.yaml")
        elif "pgi" in self.spec.variants["compiler"][0]:
            selections.append(compilers / "06-pgi-compiler.yaml")
        
        return selections

    def nvhpc_cfg(self, cuda_version):
        template = """\
compilers:
  - compiler:
    spec: nvhpc@21.3
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: cnl7
    target: any
    modules:
    - PrgEnv-nvidia
    - nvidia/21.3
    environment: {}
    extra_rpaths: [] 
"""
        return template.format(x=cuda_version)

    def cuda_config(self, cuda_version):
        if cuda_version == "10.2.89":
            return """\
packages:
  - spec: cuda@10.2.89
    prefix: /opt/nvidia/cudatoolkit10.2/10.2.89_3.28-2.1__g52c0314
"""
        else:
            full_version={
                "11.0.207": "11.0",
                "11.1.0": "11.1",
                "11.2.0": "11.2",
            }
            template = """\
packages:
  cuda:
    externals:
    - spec: cuda@{x}
      prefix: /usr/local/cuda-{y}
"""     
            truncated_version=full_version.get(cuda_version)       
            return template.format(x=cuda_version, y=truncated_version)

    def sw_description(self):
        """This is somewhat vestigial: for the Tioga config that is committed
        to the repo, multiple instances of mpi/compilers are stored and
        and these variables were used to choose consistent dependencies.
        The configs generated by this class should only ever have one
        instance of MPI etc., so there is no need for that. The experiments
        will fail if these variables are not defined though, so for now
        they are still generated (but with more-generic values).
        """
        return f"""\
software:
  packages:
    default-compiler:
      pkg_spec: "{self.spec.variants["compiler"][0]}"
    default-mpi:
      pkg_spec: cray-mpich@7.7.18
"""
