# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0
repos:
  experiments: [../experiments, ../experiments/test]
  systems: [../systems]
  applications: [../repos/ramble_applications]
  packages: [../repos/spack_repo/benchpark]
