# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

software:
  packages:
    default-compiler:
      pkg_spec: gcc@7.3.1
    default-mpi:
      pkg_spec: openmpi@4.1.5-gcc731
    compiler-gcc:
      pkg_spec: gcc@7.3.1
    lapack:
      pkg_spec: lapack@3.4.2
    mpi-gcc:
      pkg_spec: openmpi@4.1.5-gcc731
