# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

system_definition:
  name: LUMI-zen3-MI250X-Slingshot
  site: CSC
  system: LUMI-zen3-MI250X-Slingshot
  integrator:
    vendor: HPECray
    name: EX235a
  processor:
    vendor: AMD
    name: EPYC-Zen3
    ISA: x86_64
    uArch: zen3
  accelerator:
    vendor: AMD
    name: MI250X
    ISA: GCN
    uArch: gfx90a
  interconnect:
    vendor: HPECray
    name: Slingshot11
  system-tested:
    site: CSC
    name: LUMI
    installation-year: 2023
    description: top500 <https://www.top500.org/system/180048>
  top500-system-instances:
    - Frontier (ORNL)
    - LUMI     (CSC)
    - Tioga    (LLNL)
