spack:
  packages:
    default-compiler:
      spack_spec: gcc@12.1.1
    default-mpi:
      spack_spec: mvapich2@2.3.7-gcc1211
    gcc1211:
      spack_spec: gcc@12.1.1
    intel202160classic:
      spack_spec: intel@2021.6.0-classic
    lapack:
      spack_spec: intel-oneapi-mkl@2022.1.0
    mpi-{compilers}:
      spack_spec: mvapich2@2.3.7-{compilers}
