# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

software:
  packages:
    default-compiler:
      pkg_spec: gcc@9.3.0 # cce@12.0.3
    default-mpi:
      pkg_spec: cray-mpich@7.7.18
    compiler-gcc:
      pkg_spec: gcc@9.3.0
