# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

variables:
  batch_time: '02:00'
  pre_process: ''
  mpi_command: 'srun -N {n_nodes} -n {n_ranks}'
  post_process: ''
  batch_submit: 'sbatch {execute_experiment}'
  batch_nodes: '#SBATCH -N {n_nodes}'
  batch_ranks: '#SBATCH -n {n_ranks}'
  batch_timeout: '#SBATCH -t {batch_time}:00'
  default_cuda_version: '11.2.0'
  cuda_arch: '60'
  enable_mps: '/usr/tcetmp/bin/enable_mps'
