# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

spack:
  packages:
    default-compiler:
      spack_spec: gcc@=12.3.0
    default-mpi:
      spack_spec: openmpi@4.1.5
    compiler-gcc:
      spack_spec: gcc@=12.3.0
    cublas-cuda:
      spack_spec: cublas@{default_cuda_version}
    blas:
      spack_spec: openblas@0.3.23
    lapack:
      spack_spec: openblas@0.3.23