# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

system_definition:
  name: HPECray-EPYC3-MI250X-Slingshot
  manufacturer:
    vendor: HPE-Cray
    name: EX235a
  processor:
    vendor: AMD
    name: EPYC-Zen3
    ISA: x86_64
    uArch: zen3
  accelerator:
    vendor: AMD
    name: MI250X
    ISA: GCN
    uArch: gfx90a
  interconnect:
    vendor: HPE-Cray
    name: Slingshot-11
  OS:
    name: HPE-Cray-OS
  system-tested:
    owner: LLNL
    name: tioga
    installation-year: 2022
    description: [top500](https://www.top500.org/system/180052)
  top500-system-instances:
    - Frontier (ORNL)
    - Lumi (EuroHPC/CSC)
    - Tioga (LLNL)
