# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

system_definition:
  manufacturer:
    vendor: HPE-Cray
    PCB: EX235a
  processor:
    vendor: AMD
    CPU: EPYC
  accelerator:
    vendor: AMD
    GPU: MI250X
  interconnect:
    vendor: HPE-Cray
    network: Slingshot-11
  software:
    operating-system:
      name: HPE-Cray-OS
      tested: Linux/TOSS
    default-compiler:
      CPU-compiler: CCE
      GPU-compiler: ROCM
      spack_spec: cce@16.0.0-rocm5.5.1
    default-mpi:
      name: HPE-Cray-MPI
      spack_spec: cray-mpich@8.1.26%cce ~gtl
    math-library:
      - name: rocBLAS
        spack_spec: rocblas@5.5.1
      - name LAPACK
        spack_spec: cray-libsci@23.05.1.4
  system-tested:
    owner: LLNL
    name: tioga
    installation-year: 2022
    description: [top500](https://www.top500.org/system/180052)
