ramble:
  config:
    deprecated: true
    spack_flags:
      install: '--add --keep-stage'
      concretize: '-U -f'
  variables:
    mpi_command: '/usr/tcetmp/bin/lrun -n {n_ranks} -T {processes_per_node}'
    batch_submit: 'bsub {execute_experiment}'
  applications:
    raja-perf:
      workloads:
        suite:
          experiments:
            suite_{n_nodes}_{n_ranks}:
              variables:
                n_ranks: '1'
                n_nodes: '1'
  spack:
    concretized: true
    packages:
      xl2022.08.19cuda11.8.0:
        spack_spec: xl@16.1.1-2022.08.19-cuda11.8.0
      gcc831:
        spack_spec: gcc@8.3.1
      blt:
        spack_spec: 'blt@0.5.2:'
        compiler: gcc831
      cmake3231:
        spack_spec: cmake@3.23.1
        compiler: gcc831
      spectrummpi2022.08.19:
        spack_spec: spectrum-mpi@2022.08.19
      raja-perf:
        spack_spec: raja-perf@develop +cuda~openmp cuda_arch=70 ^cuda@11.8.0
        compiler: xl2022.08.19cuda11.8.0
    environments:
      raja-perf:
        packages:
        - blt
        - cmake3231
        - spectrummpi2022.08.19
        - raja-perf
