# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

packages:
  all:
    providers:
      mpi:
      - cray-mpich
      pkgconfig:
      - pkg-config
      - pkgconf
  cuda:
    externals:
    - spec: cuda@11.0.207
      prefix: /usr/local/cuda-11.0
    - spec: cuda@11.1.0
      prefix: /usr/local/cuda-11.1
    - spec: cuda@11.2.0
      prefix: /usr/local/cuda-11.2
    - spec: cuda@10.2.89
      prefix: /opt/nvidia/cudatoolkit10.2/10.2.89_3.28-2.1__g52c0314
  pkg-config:
    externals:
    - spec: pkg-config@0.29.2
      prefix: /usr
  r:
    externals:
    - spec: r@4.1.1.0
      modules:
      - cray-R/4.1.1.0
  jemalloc:
    externals:
    - spec: jemalloc@5.1.0.3
      modules:
      - cray-jemalloc/5.1.0.3
  cray-libsci:
    externals:
    - spec: cray-libsci@20.09.1
      modules:
      - cray-libsci/20.09.1
  cray-mpich:
    externals:
    - spec: cray-mpich@7.7.18
      modules:
      - cray-mpich/7.7.18
  netcdf-c:
    externals:
    - spec: netcdf-c@4.7.4.4+mpi+parallel-netcdf
      modules:
      - cray-netcdf-hdf5parallel/4.7.4.4
  petsc:
    externals:
    - spec: petsc@3.14.5.0~complex~cuda~int64
      modules:
      - cray-petsc/3.14.5.0
    - spec: petsc@3.14.5.0~complex~cuda+int64
      modules:
      - cray-petsc-64/3.14.5.0
    - spec: petsc@3.14.5.0+complex~cuda~int64
      modules:
      - cray-petsc-complex/3.14.5.0
    - spec: petsc@3.14.5.0+complex~cuda+int64
      modules:
      - cray-petsc-complex-64/3.14.5.0
  papi:
    externals:
    - spec: papi@6.0.0.9
      modules:
      - papi/6.0.0.9
