# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

import pathlib
from benchpark.directives import variant

from benchpark.system import System
from packaging.version import Version


class CscsEiger(System):

    variant(
        "compiler",
        default="gcc",
        description="Which compiler to use",
    )

    def initialize(self):
        super().initialize()

        self.gcc_version = Version("12.3.0")

        sys_variables = {
            "sys_cores_per_node": 128,
            "timeout": 30,
        }

        self.scheduler = "slurm"
        for k, v in sys_variables.items():
            setattr(self, k, v)

    def generate_description(self, output_dir):
        super().generate_description(output_dir)

        sw_description = pathlib.Path(output_dir) / "software.yaml"

        with open(sw_description, "w") as f:
            f.write(self.sw_description())

    def compiler_configs(self):
        selections = []
        compilers = CscsEiger.resource_location / "compilers"
        selections.append(compilers / "00-gcc12-compiler.yaml")

        return selections

    def external_pkg_configs(self):
        externals = CscsEiger.resource_location / "externals"

        selections = [externals / "00-packages.yaml"]

        return selections

    def sw_description(self):
        """This is somewhat vestigial: for the Tioga config that is committed
        to the repo, multiple instances of mpi/compilers are stored and
        and these variables were used to choose consistent dependencies.
        The configs generated by this class should only ever have one
        instance of MPI etc., so there is no need for that. The experiments
        will fail if these variables are not defined though, so for now
        they are still generated (but with more-generic values).
        """
        return """\
software:
  packages:
    default-compiler:
      pkg_spec: gcc@12.3.0
    default-mpi:
      pkg_spec: cray-mpich@8.1.28
    compiler-gcc:
      pkg_spec: gcc@12.3.0
"""
