ramble:
  config:
    deprecated: true
    spack_flags:
      install: '--add --keep-stage'
      concretize: '-U -f'
  variables:
    mpi_command: 'srun -N {n_nodes} -n {n_ranks}'
    batch_submit: 'sbatch {execute_experiment}'
  applications:
    saxpy:
      workloads:
        problem:
          env_vars:
            set:
              OMP_NUM_THREADS: '{n_threads}'
          variables:
            n_ranks: '8'
          experiments:
            saxpy_{n}_{n_nodes}_{n_ranks}_{n_threads}:
              variables:
                processes_per_node: ['8', '4']
                n_nodes: ['1', '2']
                n_threads: ['2', '4']
                n: ['512', '1024']
              matrices:
                - size_threads:
                  - n
                  - n_threads
  spack:
    concretized: true
    packages:
      gcc1211:
        spack_spec: gcc@12.1.1
      mvapich2237gcc1211:
        spack_spec: mvapich2@2.3.7-gcc12.1.1
      saxpy:
        spack_spec: saxpy@1.0.0 +openmp ^cmake@3.23.1
        compiler: gcc1211
    environments:
      saxpy:
        packages:
        - mvapich2237gcc1211
        - saxpy
