import argparse
import os
import shutil
import subprocess

from diffSystemSpecs import compare_yaml

import benchpark.util.color as color


def main():
    parser = argparse.ArgumentParser(
        description="""Compare ramble.yaml generated from 'experiment init' between two different commits of Benchpark.
Check if the configuration generated by 'experiment init' changed between commits.

(benchpark-python diffExperimentSpecs.py -n newCommit)

Example usage:

    $ benchpark-python diffExperimentSpecs.py -n myBranch
""",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument(
        "-o",
        "--old",
        type=str,
        default="develop",
        help="Commit hash or branch name for the old version of Benchpark (default: develop).",
    )
    parser.add_argument(
        "-n",
        "--new",
        type=str,
        required=True,
        help="Commit hash or branch name for the new version of Benchpark.",
    )
    parser.add_argument(
        "-e",
        "--experiments",
        type=str,
        nargs="*",
        default=[],
        help="List of experiments to include for comparison (default: all experiments).",
    )
    parser.add_argument(
        "-s",
        "--system",
        type=str,
        default="generic-x86",
        help="Name of system.py to use for experiment init (default: generic-x86).",
    )
    parser.add_argument(
        "-c",
        "--cluster",
        type=str,
        default=None,
        help="System variant if applicable.",
    )

    args = parser.parse_args()

    # Use the arguments provided by the user or the defaults
    bp = {
        "benchpark-old": args.old,
        "benchpark-new": args.new,
    }
    system = args.system
    cluster = args.cluster if args.cluster else system

    if args.experiments == []:
        experiments_out = subprocess.run(
            ["benchpark", "list", "experiments", "--no-title"],
            text=True,
            capture_output=True,
        )
        experiments = experiments_out.stdout.replace(" ", "")
        experiments = experiments.split("\n")
        experiments = [e for e in experiments if "+" in e]
    else:
        experiments = args.experiments

    for name, tag in bp.items():

        if name not in os.listdir(os.getcwd()):
            subprocess.run(
                ["git", "clone", "https://github.com/LLNL/benchpark.git", name]
            )
        subprocess.run(["git", "checkout", tag], cwd=name)

        if os.path.isdir(f"{name}/{cluster}"):
            shutil.rmtree(f"{name}/{cluster}")
        sys_list = [
            "python",
            f"{name}/lib/main.py",
            "system",
            "init",
            f"--dest={name}/{cluster}",
            system,
        ]
        if args.cluster:
            var = "instance_type" if system == "aws-pcluster" else "cluster"
            sys_list.append(f"{var}={cluster}")
        subprocess.run(sys_list)

        for experiment in experiments:
            subprocess.run(
                [
                    "python",
                    f"{name}/lib/main.py",
                    "experiment",
                    "init",
                    f"--dest={'/'.join(experiment.split('+'))}",
                    f"{name}/{cluster}",
                    experiment,
                ]
            )

    # Compare the YAML files
    for experiment in experiments:
        color.cprint("@*y" + experiment + "@.")
        loc = f"{cluster}/" + "/".join(experiment.split("+"))
        file = "ramble.yaml"
        color.cprint("\t@*b" + loc + "/" + file + "@.")
        compare_yaml(
            f"benchpark-old/{loc}/{file}",
            f"benchpark-new/{loc}/{file}",
        )


if __name__ == "__main__":
    main()
