# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

system_definition:
  name: AWS-Hpc7a-EPYC4-EFA
  manufacturer:
    vendor: AWS
    name: ParallelCluster3.7.2-Hpc7a
  processor:
    vendor: AMD
    name: EPYC-Zen4
    ISA_family: x86_64
    ISA: zen4
  accelerator:
    vendor: ""
    name: ""
    GPU_ISA: ""
  interconnect:
    vendor: AWS
    name: EFA
  OS:
    name: Amazon-Linux-2
  system-tested:
    owner: AWS
    name: ""
    installation-year: ""
    description: [aws/hpc7a](https://aws.amazon.com/ec2/instance-types/hpc7a)
