# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

software:
  packages:
    default-compiler:
      #pkg_spec: intel@2020b
      pkg_spec: gcc
    compiler-gcc:
      #pkg_spec: gcc@12.2.0
      pkg_spec: gcc
    compiler-intel:
      #pkg_spec: intel@2020b
      pkg_spec: intel
    default-mpi:
      #pkg_spec: intel@2020b
      pkg_spec: openmpi@4.1.4
    mpi-gcc:
      pkg_spec: openmpi@4.1.4
    blas:
      #pkg_spec: openblas@0.3.5
      pkg_spec: blas
    lapack:
      #pkg_spec: scalapack@2.0.2-openblas
      pkg_spec: lapack
