# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

spack:
  packages:
    default-compiler:
      spack_spec: gcc@12.2.0
    compiler-gcc:
      spack_spec: gcc@12.2.0
    compiler-intel:
      spack_spec: intel@2020b
    default-mpi:
      spack_spec: openmpi@4.1.4
    blas:
      spack_spec: openblas@0.3.5
    lapack:
      spack_spec: scalapack@2.0.2-openblas
