# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

spack:
  packages:
    default-compiler:
      #spack_spec: intel@2020b
      spack_spec: gcc
    compiler-gcc:
      #spack_spec: gcc@12.2.0
      spack_spec: gcc
    compiler-intel:
      #spack_spec: intel@2020b
      spack_spec: intel
    default-mpi:
      #spack_spec: intel@2020b
      spack_spec: openmpi@4.1.4
    mpi-gcc:
      spack_spec: openmpi@4.1.4
    blas:
      #spack_spec: openblas@0.3.5
      spack_spec: blas
    lapack:
      #spack_spec: scalapack@2.0.2-openblas
      spack_spec: lapack
