# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

spack:
  packages:
    default-compiler:
      spack_spec: gcc@12.3.0
    default-mpi:
      spack_spec: cray-mpich@8.1.28
    compiler-gcc:
      spack_spec: gcc@12.3.0
