# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

import pathlib
from benchpark.directives import variant

from benchpark.system import System
from packaging.version import Version
from benchpark.paths import hardware_descriptions


class JscJuwels(System):

    id_to_resources = {
        "juwels": {
            "sys_cores_per_node": 48,
            "timeout": 120,
            "sys_gpus_per_node": 4,
            "cuda_arch": '"80"',
            "system_site": "jsc",
            "hardware_key": str(hardware_descriptions)
            + "/Atos-rome-A100-Infiniband/hardware_description.yaml"
        }
    }

    variant(
        "compiler",
        default="gcc",
        description="Which compiler to use",
    )

    def initialize(self):
        super().initialize()

        self.cuda_version = Version("12.2.0")

        if self.spec.satisfies("compiler=gcc"):
            self.gcc_version = Version("12.3.0")
            self.nvhpc_version = Version("23.7")

        self.scheduler = "slurm"
        attrs = self.id_to_resources.get("juwels")
        for k, v in attrs.items():
            setattr(self, k, v)

    def generate_description(self, output_dir):
        super().generate_description(output_dir)

        sw_description = pathlib.Path(output_dir) / "software.yaml"

        with open(sw_description, "w") as f:
            f.write(self.sw_description())

    def system_specific_variables(self):
        return {"cuda_arch": self.cuda_arch}

    def compiler_configs(self):
        selections = []
        compilers = JscJuwels.resource_location / "compilers"

        if self.spec.satisfies("compiler=gcc"):
            selections.append(compilers / "00-gcc-12-compiler.yaml")
        selections.append(compilers / "01-nvhpc-compiler.yaml")
        return selections

    def external_pkg_configs(self):
        externals = JscJuwels.resource_location / "externals"

        selections = [externals / "packages.yaml"]

        cuda_cfg_path = self.next_adhoc_cfg()
        with open(cuda_cfg_path, "w") as f:
            f.write(self.cuda_config())
        selections.append(cuda_cfg_path)

        return selections

    def cuda_config(self):
        return """\
packages:
  cuda:
    buildable: false
    externals:
    - spec: cuda@{self.cuda_version}
      prefix: /p/software/juwelsbooster/stages/2024/software/CUDA/{self.cuda_version.major}
      modules:
          - Stages/2024
          - CUDA/{self.cuda_version.major}
          - NVHPC/23.7-CUDA-{self.cuda_version.major}
  curand:
    externals:
    - spec: curand@{self.cuda_version}
      prefix: /p/software/juwelsbooster/stages/2024/software/CUDA/{self.cuda_version.major}
    buildable: false
  cusparse:
    externals:
    - spec: cusparse@{self.cuda_version}
      prefix: /p/software/juwelsbooster/stages/2024/software/CUDA/{self.cuda_version.major}
    buildable: false
  cublas:
    externals:
    - spec: cublas@{self.cuda_version}
      prefix: /p/software/juwelsbooster/stages/2024/software/CUDA/{self.cuda_version.major}
    buildable: false
"""

    def sw_description(self):
        """This is somewhat vestigial: for the Tioga config that is committed
        to the repo, multiple instances of mpi/compilers are stored and
        and these variables were used to choose consistent dependencies.
        The configs generated by this class should only ever have one
        instance of MPI etc., so there is no need for that. The experiments
        will fail if these variables are not defined though, so for now
        they are still generated (but with more-generic values).
        """
        return f"""\
software:
  packages:
    default-compiler:
      pkg_spec: {self.spec.variants["compiler"][0]}
    default-mpi:
      pkg_spec: openmpi@4.1.5
    compiler-gcc:
      pkg_spec: gcc
    cublas-cuda:
      pkg_spec: cublas@{self.cuda_version}
    blas:
      pkg_spec: openblas@0.3.23
    lapack:
      pkg_spec: openblas@0.3.23
"""
