# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

spack:
  packages:
    default-compiler:
      spack_spec: '{compiler_spec}'
    default-mpi:
      spack_spec: '{mpi_spec}'
    compiler-gcc:
      spack_spec: gcc@12.1.1
    compiler-intel:
      spack_spec: intel@2021.6.0-classic
    blas:
      spack_spec: '{blas_spec}'
    lapack:
      spack_spec: '{lapack_spec}'
    mpi-gcc:
      spack_spec: mvapich2@2.3.7-gcc1211
    mpi-intel:
      spack_spec: mvapich2@2.3.7-intel202160classic
