name: Run a Set of Tests to Collect Code Coverage for Benchpark
on:
  workflow_call:
    secrets:
      BENCHPARK_CODECOV_TOKEN:
        required: true
jobs:
  run_unit_tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Benchpark
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Add needed Python libs
        run: |
          pip install -r ./requirements.txt
      - name: Run unit tests with coverage
        run: |
          ./bin/benchpark unit-test --cov=./ --cov-branch --cov-report=xml --durations=20 -ra
      - name: Upload coverage to Codecov
        if: ${{ !contains(github.head_ref, 'dependabot/') && (github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork) }}
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.BENCHPARK_CODECOV_TOKEN }}
          directory: ./coverage/reports
          files: /home/runner/work/benchpark/benchpark/coverage.xml
          flags: unittests
          verbose: true
          fail_ci_if_error: true
