on:
  workflow_call:
    inputs:
      modified_repo_dirs:
        required: true
        type: string
jobs:
  diffPackages:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Add needed Python libs
        run: |
          pip install -r ./requirements.txt
      - name: Check Packages Against Spack
        run: |-
          ./bin/benchpark-python lib/scripts/diffPackageCommits.py --packages "${{ inputs.modified_repo_dirs }}"
