on:
  workflow_call:
    inputs:
      modified_repo_dirs:
        required: true
        type: string
jobs:
  diffPackages:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Add needed Python libs
        run: |
          pip install -r ./requirements.txt
      - name: Check Packages Against Spack
        run: |-
          ./bin/benchpark-python lib/scripts/diffPackageCommits.py --packages "${{ inputs.modified_repo_dirs }}"
