on:
  workflow_call:
    inputs:
      modified_repo_dirs:
        required: true
        type: string
jobs:
  diffPackages:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Add needed Python libs
        run: |
          pip install -r ./requirements.txt
      - name: Check Packages Against Spack
        run: |-
          ./bin/benchpark-python lib/scripts/diffPackageCommits.py --packages "${{ inputs.modified_repo_dirs }}"
