name: label
on:
  pull_request_target:
    branches:
      - develop

jobs:
  pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9
