name: License Checks
on:
  workflow_call:
jobs:
  verify-license:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
      - name: Set up Python 3.11
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: '3.11'
      - name: Verify license headers
        run: |-
          python .github/workflows/bin/license verify
