name: Run Benchpark and Simple Benchmark Suite
on:
  workflow_call:
    secrets:
      BENCHPARK_CODECOV_TOKEN:
        required: true
jobs:
  saxpy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Benchpark
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Add needed Python libs
        run: |
          pip install -r ./requirements.txt
      - name: Build Saxpy Workspace
        run: |
          ./bin/benchpark experiment init --dest=saxpy/openmp saxpy+openmp
          ./bin/benchpark system init --dest=generic-x86 generic-x86
          ./bin/benchpark setup saxpy/openmp generic-x86 workspace/
      - name: Setup Ramble & Spack
        run: |
          . workspace/setup.sh
          spack mirror add ci-buildcache oci://ghcr.io/llnl/benchpark-binary-cache
          spack config add "packages:all:target:[x86_64_v3]"
          env | grep SPACK >> "$GITHUB_ENV"
          env | grep RAMBLE >> "$GITHUB_ENV"
          echo "PATH=$PATH" >> "$GITHUB_ENV"
      - name: Setup Saxpy Workspace
        working-directory: ./workspace/saxpy/openmp/generic-x86/workspace/
        run: |
          ramble \
            --workspace-dir . \
            --disable-progress-bar \
            --disable-logger \
            -c config:spack_flags:install:'--no-check-signature' \
            workspace setup
      - name: Run Saxpy Experiments
        working-directory: ./workspace/saxpy/openmp/generic-x86/workspace/
        run: |
          ramble \
            --workspace-dir . \
            --disable-progress-bar \
            --disable-logger \
            on \
            --executor '{execute_experiment}' \
            --where '{n_nodes} == 1'
      - name: Analyze Saxpy Results
        working-directory: ./workspace/saxpy/openmp/generic-x86/workspace/
        run: |
          ramble \
            --workspace-dir . \
            --disable-progress-bar \
            --disable-logger \
            workspace analyze
      - name: Archive Experiment Workspace
        working-directory: ./workspace/saxpy/openmp/generic-x86/workspace/
        if: always()
        run: |
          ramble \
            --workspace-dir . \
            --disable-progress-bar \
            --disable-logger \
            workspace archive
      - name: Upload Workspace Archive as CI Artifact
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: workspace-archive
          path: ./workspace/saxpy/openmp/generic-x86/workspace/archive/**
      - name: Upload Binaries to CI Cache
        if: github.ref == 'refs/heads/develop'
        run: |
          spack mirror set \
            --push \
            --oci-username ${{ github.actor }} \
            --oci-password "${{ secrets.GITHUB_TOKEN }}" \
            ci-buildcache
          spack buildcache push \
            -j $(($(nproc) + 1)) \
            --base-image ubuntu:24.04 \
            --unsigned \
            --update-index ci-buildcache \
            $(spack find --format '/{hash}')
      - name: Test Execution Using Binary
        run: |
          OUTPUT=$(spack find --paths saxpy)
          SAXPY_PATH=$(echo "$OUTPUT" | grep 'saxpy@' | awk '{print $2}')/bin/saxpy
          echo "Extracted Path: $SAXPY_PATH"
          ./bin/benchpark experiment init --dest=saxpy/binary saxpy+openmp package_manager="user-managed" append_path="$SAXPY_PATH"
          ./bin/benchpark setup saxpy/openmp generic-x86 workspace-binary/
          ./workspace-binary/ramble/bin/ramble \
            --disable-progress-bar \
            --workspace-dir \
            /home/runner/work/benchpark/benchpark/workspace-binary/saxpy/openmp/generic-x86/workspace \
            workspace setup
          ./workspace-binary/ramble/bin/ramble \
            --disable-progress-bar \
            --workspace-dir \
            /home/runner/work/benchpark/benchpark/workspace-binary/saxpy/openmp/generic-x86/workspace \
            on \
            --executor '{execute_experiment}' \
            --where '{n_nodes} == 1'
  dryrunexperiments:
    runs-on: ubuntu-24.04
    strategy:
      # Don't fail other running testtype tests
      fail-fast: false
      matrix:
        testtype:
          - cuda
          - rocm
          #- openmp
          #- mpi
          #- strong
          #- weak
          #- throughput
          #- modifiers
    steps:
      - name: Checkout Benchpark
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Add needed Python libs
        run: |
          pip install -r ./requirements.txt
      - name: Run Dryruns
        run: |
          ./bin/benchpark bootstrap
          BENCHPARK_RUN_COVERAGE=${{ matrix.testtype }} ./bin/benchpark-python .github/utils/dryruns.py --test ${{ matrix.testtype }}
      # - name: Upload coverage data
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage-data
      #     path: ./coverage-data
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.BENCHPARK_CODECOV_TOKEN }}
          directory: ./coverage-data-${{ matrix.testtype }}
          flags: dryrunexperiments-${{ matrix.testtype }}
          verbose: true
          fail_ci_if_error: true
  # upload_coverage:
  #   needs: dryrunexperiments
  #   runs-on: ubuntu-24.04
  #   steps:
      # - name: Download coverage data
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: coverage-data
      #     path: ./coverage-data
  pytest:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Benchpark
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Add needed Python libs
        run: |
          pip install -r ./requirements.txt
      - name: Run
        run: |-
          ./bin/benchpark unit-test
