# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

compilers:
  - compiler:
      spec: gcc@7.5.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: sles15
      target: any
      modules: []
      environment:
        append_path:
          PKG_CONFIG_PATH: /usr/lib64/pkgconfig
      extra_rpaths: []
  - compiler:
      spec: gcc@11.2.0
      paths:
        cc: /opt/cray/pe/gcc/11.2.0/bin/gcc
        cxx: /opt/cray/pe/gcc/11.2.0/bin/g++
        f77: /opt/cray/pe/gcc/11.2.0/bin/gfortran
        fc: /opt/cray/pe/gcc/11.2.0/bin/gfortran
      flags: {}
      operating_system: sles15
      target: any
      modules: []
      environment:
        prepend_path:
          LD_LIBRARY_PATH: /opt/cray/pe/pmi/6.1.12/lib:/opt/cray/libfabric/1.15.2.0/lib64
          PKG_CONFIG_PATH: /usr/lib64/pkgconfig
      extra_rpaths: []
  - compiler:
      spec: gcc@12.2.0
      paths:
        cc: /opt/cray/pe/gcc/12.2.0/bin/gcc
        cxx: /opt/cray/pe/gcc/12.2.0/bin/g++
        f77: /opt/cray/pe/gcc/12.2.0/bin/gfortran
        fc: /opt/cray/pe/gcc/12.2.0/bin/gfortran
      flags: {}
      operating_system: sles15
      target: any
      modules: []
      environment:
        prepend_path:
          LD_LIBRARY_PATH: /opt/cray/pe/pmi/6.1.12/lib:/opt/cray/libfabric/1.15.2.0/lib64
          PKG_CONFIG_PATH: /usr/lib64/pkgconfig
      extra_rpaths: []
  - compiler:
      spec: cce@14.0.2
      paths:
        cc: /opt/cray/pe/cce/14.0.2/bin/craycc
        cxx: /opt/cray/pe/cce/14.0.2/bin/crayCC
        f77: /opt/cray/pe/cce/14.0.2/bin/crayftn
        fc: /opt/cray/pe/cce/14.0.2/bin/crayftn
      flags: {}
      operating_system: sles15
      target: any
      modules: []
      environment:
        set:
          RFE_811452_DISABLE: '1'
        prepend_path:
          LD_LIBRARY_PATH: /opt/cray/pe/pmi/6.1.12/lib
        append_path:
          LD_LIBRARY_PATH: /opt/cray/pe/gcc-libs
          PKG_CONFIG_PATH: /usr/lib64/pkgconfig
      extra_rpaths:
      - /opt/cray/pe/gcc-libs
  - compiler:
      spec: cce@15.0.1
      paths:
        cc: /opt/cray/pe/cce/15.0.1/bin/craycc
        cxx: /opt/cray/pe/cce/15.0.1/bin/crayCC
        f77: /opt/cray/pe/cce/15.0.1/bin/crayftn
        fc: /opt/cray/pe/cce/15.0.1/bin/crayftn
      flags: {}
      operating_system: sles15
      target: any
      modules: []
      environment:
        set:
          RFE_811452_DISABLE: '1'
        prepend_path:
          LD_LIBRARY_PATH: /opt/cray/pe/pmi/6.1.12/lib
        append_path:
          LD_LIBRARY_PATH: /opt/cray/pe/gcc-libs
          PKG_CONFIG_PATH: /usr/lib64/pkgconfig
      extra_rpaths:
      - /opt/cray/pe/gcc-libs
  - compiler:
      spec: cce@16.0.1
      paths:
        cc: /opt/cray/pe/cce/16.0.1/bin/craycc
        cxx: /opt/cray/pe/cce/16.0.1/bin/crayCC
        f77: /opt/cray/pe/cce/16.0.1/bin/crayftn
        fc: /opt/cray/pe/cce/16.0.1/bin/crayftn
      flags: {}
      operating_system: sles15
      target: any
      modules: []
      environment:
        set:
          RFE_811452_DISABLE: '1'
        prepend_path:
          LD_LIBRARY_PATH: /opt/cray/pe/pmi/6.1.12/lib
        append_path:
          LD_LIBRARY_PATH: /opt/cray/pe/gcc-libs
          PKG_CONFIG_PATH: /usr/lib64/pkgconfig
      extra_rpaths:
      - /opt/cray/pe/gcc-libs
  - compiler:
        spec: rocmcc@5.6.1
        paths:
          cc:  /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1/bin/amdclang
          cxx: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1/bin/amdclang++
          f77: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1/bin/amdflang
          fc:  /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1/bin/amdflang
        flags: {}
        operating_system: sles15
        target: any
        modules: []
        environment:
          set:
            RFE_811452_DISABLE: '1'
          append_path:
            LD_LIBRARY_PATH: /opt/cray/pe/gcc-libs
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/pe/pmi/6.1.12/lib
            LIBRARY_PATH:  /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1/lib:/appl/lumi/SW/CrayEnv/EB/rocm/5.6.1/lib64
        extra_rpaths:
        - /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1/lib
        - /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1/lib64
        - /opt/cray/pe/gcc-libs
