# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

zips:
  AWS_Hpc7a_conf:
  - sys_instance_names
  - sys_cores_per_node
  - sys_mem_per_node
